openapi: "3.0.1"
info:
  title: "ImportApiGateway"
  version: "2023-12-03 18:58:06UTC"
servers:
- url: "https://1cixh8npm5.execute-api.eu-north-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
tags:
- name: "aws:cloudformation:stack-id"
  x-amazon-apigateway-tag-value: "arn:aws:cloudformation:eu-north-1:064281145107:stack/ImportServiceStack/098851b0-9203-11ee-b294-0e3ad7594136"
- name: "aws:cloudformation:stack-name"
  x-amazon-apigateway-tag-value: "ImportServiceStack"
- name: "aws:cloudformation:logical-id"
  x-amazon-apigateway-tag-value: "ImportApiGatewayC9176289"
paths:
  /import:
    get:
      summary: Get signed file import endpoint
      security:
        - Auth: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewSignedUrl"
        "400":
          description: Error
        "500":
          description: Server Error
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-north-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-north-1:064281145107:function:importProductsFile/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "*"
  allowHeaders:
  - "authorization"
  - "content-type"
  - "x-amz-date"
  - "x-amz-security-token"
  - "x-amz-user-agent"
  - "x-api-key"
  maxAge: -42
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"
components:
  securitySchemes:
    Auth:
      type: http
      scheme: basic
  schemas:
    NewSignedUrl:
      type: object
      properties:
        url:
          type: string
